### ISSUE TITLE
Instagram is not supported :(

### ISSUE THREAD

**Issue by is1394** [deepakaggarwal7/react-social-login#10]

**Comment by nicolas-goudry** [comment]
Thanks for your feedback.

For now, I don't think it's planned to add Instagram, neither any other social provider other than facebook, google and linkedin.

**Comment by nicolas-goudry** [comment]
@is1394 I added Instagram support on my fork – see [nicolas-goudry/react-social-login:feature/instagram](https://github.com/nicolas-goudry/react-social-login/tree/feature/instagram).

It is for now unavailable on the main repo because we have to merge the next major release code – see [nicolas-goudry/react-social-login:HOC_transform](https://github.com/nicolas-goudry/react-social-login/tree/HOC_transform) – before merging this one.

I’ll keep you updated about that as soon as I can.

**Comment by deepakaggarwal7** [comment]
instagram integrated by Nicolas
