### ISSUE TITLE
Feature Request: Github & AWS Oauth 

### ISSUE THREAD

**Issue by vinicius5581** [deepakaggarwal7/react-social-login#18]
Support to Github & AWS as providers.

**Comment by nicolas-goudry** [comment]
@vinicius5581 Thanks for your feedback.

I’ll see what I can do :wink:

**Comment by nicolas-goudry** [comment]
@vinicius5581 I added GitHub support for v3 as you can see (waiting for merge and npm release).

I didn’t digg into AWS yet and won’t have time to in next days.

I’ll keep you updated.

**Comment by nicolas-goudry** [comment]
@vinicius5581 I just removed GitHub OAuth support because GitHub doesn’t provide any way to get an access token without having to provide `client_secret`.

As react-social-login is a front-end library, we cannot use `client_secret` because it will be available to anyone reading your code.

I falled back to using personal tokens to query GitHub API and am planning to add support for OAuth login through a server of your own that will have to fetch the access token and send it back to rsl (usual `POST` request).

If you have any other idea on how to implement it, please let me know :smiley:

**Comment by nicolas-goudry** [comment]
Sorry for spam, GitHub OAuth support added in merge request #19. You’ll need a backend server to fetch GitHub access token, an example working with demo is available [here](https://github.com/nicolas-goudry/rsl-oauth-support).

**Comment by nicolas-goudry** [comment]
@vinicius5581 Support for GitHub and Amazon added, can you close please? Thanks
