### ISSUE TITLE
Incorrect User id for Github Login?

### ISSUE THREAD

**Issue by Sihui** [deepakaggarwal7/react-social-login#47]
Tried the demo, user id returned from Github login did not match my Github user id.

The user id for facebook login confused me as well.

![screen shot 2017-10-13 at 7 14 59 am](https://user-images.githubusercontent.com/3139206/31552968-cfa37fa4-afed-11e7-8f4a-9ef07b4ca658.png)

**Comment by nicolas-goudry** [comment]
Thanks for reporting @Sihui, I'll dig into this issue soon.

**Comment by nicolas-goudry** [comment]
Here is what I found about this issue:

## Facebook

I couldn’t find a way to retrieve the « original » facebook user id as you’d expect it, because, as it’s stated in their doc about retrieved `id`, « This ID is unique to each app and cannot be used across different apps. »

I did not even found any way to get user’s `username` (the one making your unique facebook profile url, i.e. `https://facebook.com/username`)... If you find anything about this, I’ll gladly fix it.

## GitHub

Thanks for spotting this, I used the wrong field from gh graphQL endpoint. It will be fixed in next release, closing this issue. Of course, feel free to reopen an issue about facebook id.
