### ISSUE TITLE
No working after hosting. 

### ISSUE THREAD

**Issue by KARTIK01** [deepakaggarwal7/react-social-login#68]
i have implemented G+, FB, Linkedin login and Code is working fine on my local machine, but after making production build, then on clicking on login button on hosted environment, no pop-up is opening and its giving error in onLoginFailure **Fetching user...** on 2nd time button click, on all social login.
Do have to implement something else on hosted env ?

**Comment by MaxInMoon** [comment]
@KARTIK01 did you try with the `3.4.0` and the `3.2.1` versions?

**Comment by nicolas-goudry** [comment]
@KARTIK01 I’ll deploy a working hosted version to GitHub Pages this evening.

Regarding your bug, can you please tell us which version you are using?

**Comment by KARTIK01** [comment]
@nicolas-goudry  thanks for demo.
well  i am using react v - 15.5.4 and react-social-login v -3.2.0

**Comment by nicolas-goudry** [comment]
Thanks for the details, will take a look at that setup and will try to reproduce it on gh-pages as soon as I can.

Don't you have any other error on loading in console ? Do you have an adblocker ? Because SDK's are sometimes flagged as trackers by adblockers.

**Comment by KARTIK01** [comment]
Problem is resolved, there was some conflict in npm packages. I have updated all packages used in project then delete node modules, then reinstall them, it fixed this problem.

**Comment by avocadojesus** [comment]
I am having this same issue. Any idea what packages needed to be updated to make this work? our app is stuck in react 15, so i cannot up the version here. stuck at `react-social-login @3.2.0` and `react 15.6.2`. Still looking for a workaround. when I log the error, it just says `Fetching User` with no explanation. monitoring the network, i don't see any XHR requests departing, and the error message only happens when you click the button multiple times quickly. Clicking the button a single time seems to do absolutely nothing, but weirdly works fine in my local environment. Only seems to be breaking when the bundle file is hosted on an s3-cloudfront stack. I have tried removing all CSP headers from my requests, but this does not seem to stop the issue. I have also tried using an incognito chrome window, as well as removing and rebuilding node_modules using `npm install`. Is there anything I can do aside form upgrading to React @16?
