### ISSUE TITLE
Warning: Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by vleango** [deepakaggarwal7/react-social-login#75]
I am getting this warning when using `SocialButton.js`

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail
```
Not really sure what this all means...
I am using React 16.1.1

**Comment by atanasster** [comment]
@vleango , just create it as a react class component:
class SocialButton  extends Component {
    render() {
        const {children, triggerLogin, ...props} = this.props;
        return (
            <Button onClick={triggerLogin} {...props}>
                {children}
            </Button>
        )
    }
}

export default SocialLogin(SocialButton)

**Comment by nicolas-goudry** [comment]
@vleango Yeah, this is kinda « normal ».

We use a ref to `WrappedComponent` in order to trigger the logout function from this ref.

I’ll use refs only if `WrappedComponent` is not stateless, but be aware that logout function will not be available if `rsl` is not mounted, eg: demo example wouldn’t work with stateless `SocialButtons`.

For now, @atanasster is perfectly right, you should stick to stateful components ;)

**Comment by nicolas-goudry** [comment]
@vleango When I’ll release, just clone the repo and change code of `demo/components/socialButton.js` by the following:

```javascript
import React from 'react'

import SocialLogin from '../../src/index'

const Button = ({ children, triggerLogin, triggerLogout, ...props }) => (
  <div
    onClick={triggerLogin}
    style={{
      background: '#eee',
      border: '1px solid black',
      borderRadius: '3px',
      display: 'inline-block',
      margin: '5px',
      padding: '10px 20px'
    }}
    {...props}
  >
    { children }
  </div>
)

export default SocialLogin(Button)
```

Just launch the demo (`npm start`) and see that there is no error anymore 🎊  but logout functionality can’t be triggered anymore.
